### ISSUE TITLE
Would you be interested in adding this to JuliaLang's package listing?

### ISSUE THREAD

**Issue by phaverty** [rasmushenningsson/SMSSVD.jl#2]
I can help with that. Having SMSSVD install from the common set of packages would make it easier for users to find SMSSVD. This would also make it easier for organizations, such as ours :-), to maintain a shared set of packages that work together.

**Comment by rasmushenningsson** [comment]
I've submitted a pull request to METADATA now. I hope it will go live soon.
You are right that it's a much better way to keep things organized!

**Comment by phaverty** [comment]
Great! I've found this [Attobot](https://discourse.julialang.org/t/attobot-a-package-release-bot/494/2) tool very helpful when bumping the version number.  (Basically, you just add a tag/release through the GitHub website and the rest is automated.) Using the julia Pkg.* tools manually was problematic at times.

**Comment by rasmushenningsson** [comment]
Yeah I will definitely try that next time. Thank. It was indeed cumbersome to do it from julia.

**Comment by rasmushenningsson** [comment]
Now it's added to the METADATA. I had to rename the package to SubMatrixSelectionSVD to conform to the naming standards.
Thank you for all your suggestions. Do tell me if you have some other input!
